# version: '2.2'
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       ENV: development
#     command: bundle exec jekyll serve
#     volumes:
#       - '.:/ruby-app'
#     ports:
#       - "4000:4000"
version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
